services:
  - type: web
    name: ai-roast-me-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
